export default {
  brand: {
    name: 'Oscar Palma',
    subtitle: 'LANDSCAPE · GARDEN STUDIO',
    location: 'Región Metropolitana · Chile',
    whatsapp: '+56 9 3584 2045',
    whatsappRaw: '56935842045',
    whatsappUrl: 'https://wa.me/56935842045?text=Hola%2C%20me%20interesa%20una%20evaluaci%C3%B3n%20gratuita%20de%20mi%20espacio%20exterior.',
    email: 'contacto@oscarpalma.cl',
    coverage: 'Vitacura, Las Condes, Lo Barnechea, Providencia, Ñuñoa, La Reina, Peñalolén, Chicureo, Colina y alrededores.',
    hours: 'Lunes a viernes 9:00–18:00 · Sábado 9:00–13:00',
  },

  hero: {
    eyebrow: 'Paisajismo · Diseño · Jardinería · Santiago',
    titleA: 'Jardines que envejecen',
    titleB: 'con intención.',
    lead: 'Diseñamos y construimos jardines sustentables, ornamentales y de bajo mantenimiento. Hechos a medida para la Región Metropolitana — y pensados para verse mejor cada temporada.',
    primaryCta: 'Solicitar evaluación gratuita',
    secondaryCta: 'Ver portafolio',
    stats: [
      ['12', 'años de experiencia'],
      ['140+', 'jardines entregados'],
      ['RM', 'cobertura regional'],
    ],
    photo: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=1800&q=80',
  },

  trust: {
    eyebrow: 'Confianza',
    title: 'Doce años diseñando jardines que funcionan.',
    metrics: [
      ['140+', 'proyectos entregados'],
      ['98%', 'clientes nos recomiendan'],
      ['30%', 'menos consumo hídrico promedio'],
      ['12', 'años en la industria'],
    ],
    logos: [
      { name: 'Casacor', context: 'Proyecto destacado 2022' },
      { name: 'Revista ED', context: 'Edición jardines sustentables' },
      { name: 'Grupo Patio', context: 'Diseño de áreas verdes' },
      { name: 'Fundación Mustakis', context: 'Paisajismo institucional' },
      { name: 'Colegio Tabancura', context: 'Áreas verdes educativas' },
    ],
  },

  types: [
    {
      key: 'lowwater',
      name: 'Bajo consumo hídrico',
      tag: 'Xerojardinería',
      desc: 'Especies resistentes a la sequía, riego eficiente y mulching. Menos agua, más carácter.',
      detail: 'Diseñamos con plantas adaptadas a la sequía de la Región Metropolitana: lavándulas, agaves, rosmarinos, salvias y gramíneas resistentes. El resultado es un jardín que consume hasta un 40% menos de agua sin sacrificar belleza.',
      bullets: ['−40% consumo de agua', 'Bajo mantenimiento', 'Ideal para climas secos', 'Mulching incluido'],
      for: 'Propietarios que quieren un jardín atractivo con factura de agua baja.',
      photo: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'ornamental',
      name: 'Ornamental · floración',
      tag: 'Estación',
      desc: 'Paletas de floración escalonada, follajes contrastantes y arquitectura vegetal.',
      detail: 'Diseñamos con flores que se relevan durante el año: rosales, lavándulas, hortensias, salvias y bulbosas de temporada. El jardín siempre tiene color, sin importar el mes.',
      bullets: ['Floración todo el año', 'Color y textura', 'Alta presencia visual', 'Paleta personalizada'],
      for: 'Quienes quieren impacto visual inmediato y jardín siempre vistoso.',
      photo: 'https://images.unsplash.com/photo-1558603668-6570496b66f8?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'zen',
      name: 'Zen · asiático',
      tag: 'Contemplativo',
      desc: 'Piedra, agua, grava rastrillada y vegetación controlada. Un jardín para habitar la calma.',
      detail: 'Bambúes, liriopes, rocas de río, grava blanca y agua en movimiento. Diseño minimalista que invita a detenerse. Muy bajo mantenimiento si se diseña bien desde el inicio.',
      bullets: ['Composición minimalista', 'Materiales naturales', 'Espacio para pausa', 'Muy bajo mantenimiento'],
      for: 'Personas que buscan un rincón de tranquilidad y diseño refinado.',
      photo: 'https://images.unsplash.com/photo-1578898887932-dce23a595ad4?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'lowmaint',
      name: 'Bajo mantenimiento',
      tag: 'Set and forget',
      desc: 'Para clientes ocupados. Diseño pensado para requerir visitas mínimas sin perder belleza.',
      detail: 'Seleccionamos especies longevas, resistentes a plagas y de crecimiento lento. El riego tecnificado hace el trabajo diario. Tú solo disfrutas.',
      bullets: ['Visitas trimestrales', 'Plantas longevas', 'Sin pasto demandante', 'Riego automatizado'],
      for: 'Familias ocupadas que quieren jardín sin dedicarle tiempo.',
      photo: 'https://images.unsplash.com/photo-1584285418404-50a6e4d3f1d5?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'native',
      name: 'Sustentable · nativo',
      tag: 'Flora chilena',
      desc: 'Quillay, peumo, chagual, puya. Biodiversidad local que atrae polinizadores y pájaros.',
      detail: 'Un jardín que es también un fragmento de ecosistema. Usamos flora nativa chilena adaptada al clima de Santiago: quillay, peumo, litre, chagual, puya y copihue cuando las condiciones lo permiten.',
      bullets: ['Flora nativa 100%', 'Atrae fauna y polinizadores', 'Huella hídrica mínima', 'Muy resistente'],
      for: 'Personas con conciencia ambiental y conexión con la naturaleza chilena.',
      photo: 'https://images.unsplash.com/photo-1585129777188-94600bc87058?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'rooftop',
      name: 'Terrazas y rooftops',
      tag: 'Urbano',
      desc: 'Jardines en altura con carga controlada, viento y sol extremos. Privacidad verde.',
      detail: 'Diseño especializado para terrazas y azoteas: carga estructural controlada, sustratos livianos, contenedores técnicos y especies resistentes al viento. Creamos privacidad vegetal en altura.',
      bullets: ['Sustratos livianos', 'Resistencia al viento', 'Privacidad visual', 'Impermeabilización incluida'],
      for: 'Departamentos, penthouses y edificios con espacios exteriores en altura.',
      photo: 'https://images.unsplash.com/photo-1585154156160-1cc18d64eea1?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'materials',
      name: 'Piedra · madera · vegetación',
      tag: 'Arquitectónico',
      desc: 'Composiciones donde los materiales duros dialogan con el follaje. Estructura y suavidad.',
      detail: 'Decks de madera nativa o tratada, muros de piedra laja, grava de río y vegetación estructural. El jardín como extensión arquitectónica de la vivienda.',
      bullets: ['Deck de madera', 'Piedra local', 'Integración arquitectónica', 'Diseño cohesivo'],
      for: 'Casas de arquitectura contemporánea o quienes valoran la coherencia estética.',
      photo: 'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?auto=format&fit=crop&w=1200&q=80',
    },
    {
      key: 'seasonal',
      name: 'Jardines por estación',
      tag: 'Cuatro estaciones',
      desc: 'Diseño pensado para que el jardín tenga una escena distinta —y bella— cada temporada.',
      detail: 'Combinamos bulbosas de primavera, flores de verano, follajes de otoño y estructuras invernales. El jardín nunca es el mismo dos veces al año — y siempre tiene algo que ofrecer.',
      bullets: ['Floración continua', 'Follaje invernal de color', 'Paleta por mes', 'Siempre relevante'],
      for: 'Quienes quieren que el jardín sorprenda en cada visita.',
      photo: 'https://images.unsplash.com/photo-1597764690523-15bea4c581c9?auto=format&fit=crop&w=1200&q=80',
    },
  ],

  portfolio: [
    {
      title: 'Casa Lo Barnechea',
      style: 'Ornamental · nativo',
      size: '620 m²',
      year: '2024',
      photo: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1400&q=80',
    },
    {
      title: 'Patio Ñuñoa',
      style: 'Bajo mantenimiento',
      size: '180 m²',
      year: '2024',
      photo: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1400&q=80',
    },
    {
      title: 'Terraza Vitacura',
      style: 'Rooftop · ornamental',
      size: '95 m²',
      year: '2023',
      photo: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=80',
    },
    {
      title: 'Casa Chicureo',
      style: 'Zen · piedra',
      size: '420 m²',
      year: '2023',
      photo: 'https://images.unsplash.com/photo-1507497605863-fc6ce1f80f88?auto=format&fit=crop&w=1400&q=80',
    },
    {
      title: 'Parcela Colina',
      style: 'Xerojardín · nativo',
      size: '2.100 m²',
      year: '2023',
      photo: 'https://images.unsplash.com/photo-1551410224-699683e15636?auto=format&fit=crop&w=1400&q=80',
    },
    {
      title: 'Casa Las Condes',
      style: 'Ornamental · madera',
      size: '340 m²',
      year: '2022',
      photo: 'https://images.unsplash.com/photo-1604147706283-d7119b5b822c?auto=format&fit=crop&w=1400&q=80',
    },
  ],

  services: [
    {
      key: 'diseno',
      icon: 'ruler',
      name: 'Diseño de jardines',
      tagline: 'Del concepto al plano',
      desc: 'Partimos del espacio real: visita técnica, análisis de suelo y luz, y propuesta gráfica con paleta vegetal. Iteramos hasta que el diseño se sienta tuyo.',
      bullets: ['Visita y diagnóstico del espacio', 'Propuesta con plano a escala', 'Paleta vegetal ilustrada', 'Presupuesto detallado por etapas'],
    },
    {
      key: 'instalacion',
      icon: 'shovel',
      name: 'Instalación y construcción',
      tagline: 'Del papel al jardín real',
      desc: 'Preparación de suelo, trasplante, instalación de riego, estructuras de madera y piedra. Trabajo limpio, con plazos y responsables definidos.',
      bullets: ['Movimiento de tierra y enmiendas', 'Instalación de riego tecnificado', 'Plantación a tamaño útil', 'Terminaciones en madera y piedra'],
    },
    {
      key: 'mantencion',
      icon: 'leaf',
      name: 'Mantención periódica',
      tagline: 'Para que siga viéndose bien',
      desc: 'Planes de visita mensuales, bimestrales o trimestrales. Poda, fertilización, control de plagas y ajuste de riego por temporada.',
      bullets: ['Plan de visitas a la carta', 'Poda y fertilización orgánica', 'Control integrado de plagas', 'Informe de estado post-visita'],
    },
    {
      key: 'riego',
      icon: 'droplet',
      name: 'Sistema de riego',
      tagline: 'Agua donde se necesita',
      desc: 'Diseño e instalación de riego por goteo o microaspersión. Integrado con programador inteligente y sensor de humedad.',
      bullets: ['Diseño hidráulico personalizado', 'Goteo y microaspersión', 'Programador inteligente', 'Hasta 40% de ahorro hídrico'],
    },
    {
      key: 'asesoria',
      icon: 'sparkle',
      name: 'Asesoría profesional',
      tagline: 'Una visita que lo cambia todo',
      desc: 'Visita de consultoría para quien quiere orientación experta antes de decidir. Diagnóstico, recomendaciones concretas y estimación de inversión.',
      bullets: ['Visita de 1,5h con informe escrito', 'Diagnóstico de suelo y luz', 'Recomendaciones sin compromiso', 'Descuenta del proyecto al contratar'],
    },
    {
      key: 'renovacion',
      icon: 'house',
      name: 'Renovación de áreas verdes',
      tagline: 'Para jardines que necesitan un reinicio',
      desc: 'Recuperación de jardines descuidados o mal diseñados. Limpieza profunda, rediseño parcial y replantación selectiva.',
      bullets: ['Diagnóstico y limpieza profunda', 'Rediseño de zonas clave', 'Reemplazo de especies agotadas', 'Plan de mantención post-renovación'],
    },
  ],

  benefits: [
    { icon: 'droplet',   title: 'Ahorro de agua',       desc: 'Jardines con hasta 30% menos consumo hídrico. Mismo verde, menos gasto mensual en agua.' },
    { icon: 'leaf',      title: 'Menos mantención',      desc: 'Diseñado para verse bien sin que dediques tu fin de semana a mantenerlo. Visitas trimestrales son suficientes.' },
    { icon: 'house',     title: 'Valoriza tu propiedad', desc: 'Un jardín profesional puede aumentar el valor de tasación de tu propiedad entre un 10% y 15%. Lo que parece gasto, es inversión.' },
    { icon: 'sparkle',   title: 'Resultado desde el día uno', desc: 'Plantamos a tamaño útil. No tienes que esperar dos temporadas para que el jardín se vea bien.' },
    { icon: 'ruler',     title: 'Hecho a medida',        desc: 'No hay dos jardines iguales porque no hay dos propiedades iguales. Tu jardín se diseña desde cero, para tu espacio y tu forma de vivirlo.' },
    { icon: 'handshake', title: 'No desaparecemos',      desc: 'Te acompañamos durante el primer año completo para asegurar que el jardín tome bien y evolucione como se diseñó.' },
  ],

  process: [
    { n: '01', title: 'Evaluación del espacio', desc: 'Vamos a tu terreno sin costo. Estudiamos suelo, luz, viento y cómo usas el espacio. Sin compromiso de contratación de tu parte.' },
    { n: '02', title: 'Propuesta de diseño',    desc: 'En 5 a 7 días hábiles recibes planos, paleta vegetal y presupuesto detallado. Iteramos hasta que el diseño calce exactamente con lo que necesitas. Sin letra chica.' },
    { n: '03', title: 'Ejecución',              desc: 'Comenzamos en la fecha acordada. Preparación del suelo, instalación de riego, plantación y terminaciones. Te informamos el avance cada semana. Sin sorpresas de precio.' },
    { n: '04', title: 'Entrega y seguimiento',  desc: 'Te entregamos el jardín terminado con su manual de cuidado, y te acompañamos con visitas durante los primeros 12 meses para asegurar que tome bien.' },
  ],

  testimonials: [
    {
      quote: 'Teníamos una terraza de 95 m² completamente abandonada. Oscar propuso un diseño con flora nativa y macetas técnicas resistentes al viento. Hoy es el espacio que más usamos en la casa, y el jardín se ve mejor cada mes.',
      name: 'María José Errázuriz',
      role: 'Vitacura',
      project: 'Terraza · Flora nativa · 95 m²',
      initials: 'MJ',
    },
    {
      quote: 'Lo que más valoro es que diseñó pensando en cómo vivimos realmente el jardín — no en cómo se ve en una foto. Un año después sigue viéndose mejor que el día uno y gastamos un 30% menos en agua.',
      name: 'Cristián Vergara',
      role: 'Lo Barnechea',
      project: 'Jardín ornamental · 620 m² · 2024',
      initials: 'CV',
    },
    {
      quote: 'Tenía miedo de que el mantenimiento fuera eterno. Con el diseño que me propusieron necesito jardinero una vez al mes máximo. Ahorro agua, tengo flores casi todo el año y se ve precioso.',
      name: 'Pilar Undurraga',
      role: 'Chicureo',
      project: 'Jardín bajo mantenimiento · 420 m²',
      initials: 'PU',
    },
  ],
}
